version: "3.8"
services:
  dev_db:
    image: postgres:12.3
    environment:
      # Ensure we configure the db user below, in the local dev/test EDN files.
      # Some migrations like CREATE EXTENSION require superuser privileges,
      # which only this POSTGRES_USER has locally.
      POSTGRES_USER: chronograph_dev
      POSTGRES_DB: chronograph_dev
      POSTGRES_PASSWORD: chronograph_devpwd
    ports:
      - 19401:5432
    volumes:
      - ./dev/postgres-entrypoint.d:/docker-entrypoint-initdb.d:Z
