name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PORT: 8000
  LOGO: https://nilenso.com/images/nilenso_logos/nilenso_logo.png
  CHRONOGRAPH_JAR: chronograph.jar

jobs:
  server-test:
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_DB: chronograph_ci
          POSTGRES_USER: chronograph_ci_user
          POSTGRES_PASSWORD: chronograph_ci_pwd
        ports:
          - 5432:5432

    runs-on: ubuntu-latest

    env:
      TEST_CONFIG_FILE: "config/config.ci.edn"

    steps:
    - uses: actions/checkout@v2

    - name: Cache lein deps
      uses: actions/cache@v2
      env:
        cache-name: cache-lein-deps
      with:
        path: ~/.m2
        key: ${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ env.cache-name }}-

    - name: Install dependencies
      run: lein deps

    - name: Run migrations
      run: lein run -- -mf $TEST_CONFIG_FILE

    - name: Run tests
      run: lein test

  frontend-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install frontend deps
      run: yarn install

    - name: Run frontend tests
      run: yarn test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install clj-kondo
        run: |
          curl -sLO https://raw.githubusercontent.com/borkdude/clj-kondo/master/script/install-clj-kondo
          chmod +x install-clj-kondo
          sudo ./install-clj-kondo

      - name: Lint the source directory
        run: clj-kondo --lint src/

      - name: Lint the test directory
        run: clj-kondo --lint test/
